<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>markdown</string>
		<string>md</string>
		<string>pandoc</string>
		<string>mdown</string>
		<string>markdn</string>
	</array>
	<key>name</key>
	<string>Pandoc</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>comment</key>
			<string>Metainformation of the files such as Title, Author, Date</string>
			<key>match</key>
			<string>^(%+([^\n]+))</string>
			<key>name</key>
			<string>metainfo.source.pandoc</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Comments in HTML format</string>
			<key>match</key>
			<string>&lt;!--(.*)--&gt;</string>
			<key>name</key>
			<string>comment.pandoc</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Heading</string>
			<key>match</key>
			<string>^(={3,})(?=[ 	]*$)</string>
			<key>name</key>
			<string>markup.heading.markdown</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Heading</string>
			<key>match</key>
			<string>^(-{3,})(?=[ 	]*$)</string>
			<key>name</key>
			<string>markup.heading.markdown</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Heading</string>
			<key>match</key>
			<string>^#+([^\.]+)(.*)$</string>
			<key>name</key>
			<string>markup.heading.markdown</string>
		</dict>

		<!-- enable these to match lists -->
		<!-- 
		<dict>
			<key>comment</key>
			<string>Magic Numbered List</string>
			<key>match</key>
			<string>^\s*#\.+(\s+)(.*)$</string>
			<key>name</key>
			<string>markup.list.ordered</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Manual Numbered List</string>
			<key>match</key>
			<string>^(\s*)[\()]?\d+([\.\)])(\s+)(.*)$</string>
			<key>name</key>
			<string>markup.list.ordered</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Unordered List</string>
			<key>match</key>
			<string>^(\s*)([\*\+-]+)(\s+)(.*)$</string>
			<key>name</key>
			<string>markup.list.unordered</string>
		</dict>
		-->

		<dict>
			<key>comment</key>
			<string>Italic</string>
			<key>match</key>
			<string>\*([^\s\*][^\*]*)\*|_([^\s_][^_]*)_</string>
			<key>name</key>
			<string>punctuation.definition.italic.markdown</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Bold</string>
			<key>match</key>
			<string>\*\*([^\s\*][^\*]*)\*\*|__([^\s\*][^\*]*)__</string>
			<key>name</key>
			<string>punctuation.definition.bold.markdown</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Inline Math LaTeX</string>
			<key>match</key>
			<string>\$([^\s\$][^\$]*)\$</string>
			<key>name</key>
			<string>math.pandoc</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Math LaTeX</string>
			<key>match</key>
			<string>\$\$([^\$]+)\$\$</string>
			<key>name</key>
			<string>math.pandoc</string>
		</dict>


		<dict>
			<key>begin</key>
			<string>^\s*\[\^</string>
			<key>end</key>
			<string>\]:</string>
			<key>name</key>
			<string>footnote.num.pandoc</string>
			
			<!--
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>[A-Za-z0-9]+</string>
					<key>name</key>
					<string>footnote.num.pandoc</string>
				</dict>
			</array>
			-->
		</dict>

		<dict>
			<key>begin</key>
			<string>\[\^</string>
			<key>end</key>
			<string>\]</string>
			<key>name</key>
			<string>footnote.delim.pandoc</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>[A-Za-z0-9]+</string>
					<key>name</key>
					<string>footnote.num.pandoc</string>
				</dict>
			</array>
		</dict>
	


		<dict>
			<key>begin</key>
			<string>\[</string>
			<key>end</key>
			<string>\]</string>
			<key>name</key>
			<string>citation.bracket.pandoc</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>@[A-Za-z0-9_:]+</string>
					<key>name</key>
					<string>citation.pandoc</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>comment</key>
			<string>Reference citation</string>
			<key>match</key>
			<string>\s+@[A-Za-z0-9_:]+</string>
			<key>name</key>
			<string>citation.pandoc</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Link references</string>
			<key>match</key>
			<string>!\[(.*)\]\(.*\)</string>
			<key>name</key>
			<string>link.pandoc</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Link references</string>
			<key>match</key>
			<string>(\[.*\])+(\(http.*\))+</string>
			<key>name</key>
			<string>link.pandoc</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Link references</string>
			<key>match</key>
			<string>(\(http(.*)\))+</string>
			<key>name</key>
			<string>link.pandoc</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Footnotes and notes</string>
			<key>match</key>
			<string>^\[\^(.*)\]:(.*)$</string>
			<key>name</key>
			<string>note.pandoc</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Footnotes and notes</string>
			<key>match</key>
			<string>\^\[(.*)\]</string>
			<key>name</key>
			<string>note.pandoc</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Code block</string>
			<key>begin</key>
			<string>```</string>
			<key>end</key>
			<string>```</string>
			<key>name</key>
			<string>code.pandoc</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Code block</string>
			<key>begin</key>
			<string>~~~</string>
			<key>end</key>
			<string>~~~</string>
			<key>name</key>
			<string>code.pandoc</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Blockquote text</string>
			<key>match</key>
			<string>^(&gt;)+\s*(.*)</string>
			<key>name</key>
			<string>quote.pandoc</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>&lt;</string>
			<key>end</key>
			<string>&gt;</string>
			<key>name</key>
			<string>balise.pandoc</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\w+</string>
					<key>name</key>
					<string>balise.pandoc</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>\{</string>
			<key>end</key>
			<string>\}</string>
			<key>name</key>
			<string>tag.pandoc</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\.+</string>
					<key>name</key>
					<string>tag.pandoc</string>
				</dict>
			</array>
		</dict>
		<!--
		<dict>
			<key>comment</key>
			<string>Balise text</string>
			<key>match</key>
			<string>".+"</string>
			<key>name</key>
			<string>balise.pandoc.text</string>
		</dict>
	  -->
	</array>
	<key>scopeName</key>
	<string>text.pandoc</string>
	<key>uuid</key>
	<string>50a29d70-cec4-4462-ad8a-8f44715cb391</string>
</dict>
</plist>
